.TH SIEMMANAGE 1
.SH NAME
siemmanage - CLI tool for managing SIEM tables

.SH SYNOPSIS

\fBsiemmanage\fR [\fB-h] [\fB--version\fR] [\fB-c \fICONFIG\fR] [\fB--clear\fR] [\fB--force\fR] [\fB--importrules \fIFILE\fR] [\fB--exportrules \fIFILE\fR] [\fB--imporhelpers \fIFILE\fR] [\fB--exporthelpers \fIFILE\fR] [\fB--table \fITABLE\fR]

.SH DESCRIPTION
\fBsiemmanage\fR is a tool for clearing SIEM tables, and importing and exporting rules and helpers.

.SH OPTIONS
  
  usage: \fBsiemtrigger\fR [\fBoptions\fR]

  optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  -c CONFIG             set the config file
  --clear               delete the SQL table for selected section
  --force               really delete the table
  --importrules FILE    set a JSON file to import rules
  --exportrules FILE    set a JSON file to export rules
  --importhelpers FILE  set a JSON file to import helpers
  --exporthelpers FILE  set a JSON file to export helpers
  --table TABLE         set a table

.SH EXAMPLES
    siemmanage --importhelpers config/example_helpers.json
    siemmanage --exportfules rules.json --table RULESAuth
    siemmanage --clear --force --table Auth

.SH SEE ALSO
    siemstress(7)
    siemparse(1)
    siemquery(1)
    siemtrigger(1)

.SH FILES
    /etc/siemstress/db.conf
    /etc/siemstress/sections.conf
    /usr/share/doc/siemstress/README.md
    /usr/share/doc/siemstress/LICENSE
    /usr/share/doc/siemstress/CHANGELOG.md

.SH AUTHOR
    Dan Persons (dpersonsdev@gmail.com)

.SH COPYRIGHT
MIT License

Copyright (c) 2017 Dan Persons (dpersonsdev@gmail.com)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
